bold = true
color_mode = "rgb" # ansi, rgb or none
palette = "custom" # default, darker, pastel or matrix
custom = ["#7E9CD8", "#957FB8", "#E46876", "#98BB6C", "#E6C384", "#7FB4CA", "#FFA066"]
rainbow = 0 # 0-255
delay_ms = 20
inherit_style = false
kinds = [
    "curved",
] # heavy, light, curved, knobby, emoji, outline, dots, blocks, sus
num_pipes = 1
reset_threshold = 0.5 # 0.0–1.0
turn_chance = 0.15 # 0.0–1.0
