#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

sketchybar --bar \
    position=top \
    height=32 \
    y_offset=0 \
    margin=0 \
    corner_radius=0 \
    blur_radius=0 \
    color=$BAR_BG \
    border_width=0 \
    shadow=off

sketchybar --add event aerospace_workspace_change

source $ITEM_DIR/aerospace.sh

default=(
    padding_left=4
    padding_right=4
    icon.font="SF Pro:Semibold:14.0"
    label.font="SF Pro:Medium:13.0"
    icon.color=$FG_PRIMARY
    label.color=$FG_SECONDARY
    icon.padding_left=4
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=4
)

sketchybar --default "${default[@]}"

sketchybar --add item clock right \
    --set clock update_freq=10 icon= icon.color=$FG_SECONDARY script="$PLUGIN_DIR/clock.sh" \
    --add item battery right \
    --set battery update_freq=120 icon.color=$FG_SECONDARY script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke power_source_change

source $ITEM_DIR/front_app.sh

sketchybar --hotload on
sketchybar --update
