# -------------------- Taps --------------------
tap "felixkratz/formulae"
tap "nikitabobko/tap"
tap "joncrangle/tap"
tap "olets/tap"

# -------------------- Homebrew Formulae --------------------
brew "aria2"
brew "bash"
brew "bat"
brew "btop"
brew "coreutils"
brew "create-dmg"
brew "curl"
brew "docker"
brew "eza"
brew "fastfetch"
brew "ffmpeg"
brew "ffmpegthumbnailer"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "glow"
brew "go"
brew "gradle"
brew "imagemagick"
brew "jenv"
brew "lazygit"
brew "lua"
brew "luarocks"
brew "macmon"
brew "maven"
brew "mole"
brew "neovim"
brew "node"
brew "poppler"
brew "proto"
brew "prettier"
brew "python@3.14"
brew "pipx"
brew "ruff"
brew "scc"
brew "oh-my-posh"
brew "switchaudio-osx"
brew "tmux"
brew "tree"
brew "unar"
brew "trash"
brew "wget"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "felixkratz/formulae/sketchybar"
brew "joncrangle/tap/sketchybar-system-stats"

# -------------------- Homebrew Casks --------------------
cask "aerospace"
cask "balenaetcher"
cask "battery"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "crystalfetch"
cask "docker-desktop"
cask "font-sf-mono"
cask "font-sf-pro"
cask "font-sketchybar-app-font"
cask "ghostty"
cask "iina"
cask "intellij-idea"
cask "istat-menus"
cask "itsycal"
cask "firefox"
cask "mos"
cask "obsidian"
cask "raycast"
cask "sf-symbols"
cask "vesktop"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "utm"

# -------------------- Go Tools --------------------
go "github.com/packwiz/packwiz"
go "mvdan.cc/sh/v3/cmd/shfmt"

# -------------------- Cargo Tools --------------------
cargo "darklua"
cargo "nucleus"
cargo "tree-sitter-cli"
