[path_overrides]
vesktop=~/.config/vesktop/themes
wallpapers=~/wallpapers

[file_overrides]
starship=~/.config
VSCodium=~/.config/VSCodium/User
git=~
zsh=~
claude=~/.claude
emojis=~/.config/fontconfig/conf.d
obsidian=~/notes/.obsidian
