[path_overrides]
vesktop=~/.config/vesktop/themes
wallpapers=~/wallpapers

[file_overrides]
starship=~/.config
code=~/.config/VSCodium/User
code=~/.config/Code/User
git=~
zsh=~
claude=~/.claude
emojis=~/.config/fontconfig/conf.d
obsidian=~/notes/.obsidian

[file_links]
