# Folders not listed here get symlinked to ~/.config/<name>

[directories]
# name = "symlink_path"
vesktop = "$HOME/Library/Application Support/vesktop/themes"

[files]
# name = "target_directory"
aider = "$HOME"
zsh = "$HOME"
git = "$HOME"
vscode = "$HOME/Library/Application Support/Code/User"
