# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

theme = "elara"

[servers.soju]
nickname = "elara"
server = "100.111.24.96"
port = 6667
use_tls = false

[servers.soju.sasl.plain]
username = "elara"
password_file = "/home/elara/.config/halloy/soju-password"
