#!/bin/bash

options=(
	style=round
	width=2.0
	hidpi=off
	active_color=0xffBB99F7
	inactive_color=0xffBB99F7
	blacklist="Control Center,Notification Center,Raycast,Activity Monitor,Archive Utility"
)

borders "${options[@]}"
