#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
  layout                       bsp   \
  mouse_follows_focus          off   \
  focus_follows_mouse          autofocus \
  window_placement             second_child \
  window_shadow                off   \
  window_animation_duration    0.2   \
  window_animation_frame_rate  120   \
  window_opacity               off   \
  active_window_opacity        1.0   \
  normal_window_opacity        1.0  \
  split_ratio                  0.50  \
  split_type                   auto  \
  auto_balance                 off   \
  top_padding                  8    \
  bottom_padding               8     \
  left_padding                 8     \
  right_padding                8     \
  window_gap                   8     \
  mouse_modifier               alt   \
  mouse_action1                move  \
  mouse_action2                resize \
  mouse_drop_action            swap

# Float rules
yabai -m rule --add app="^System Settings$"   manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Calculator$"        manage=off float=on
yabai -m rule --add app="^Finder$"            manage=off float=on
yabai -m rule --add app="^Raycast$"           manage=off
yabai -m rule --add app="^Activity Monitor$"  manage=off float=on
yabai -m rule --add app="^Archive Utility$"   manage=off float=on

# Space labels
yabai -m space 1 --label terminal
yabai -m space 2 --label code
yabai -m space 3 --label browser
yabai -m space 4 --label chat
yabai -m space 5 --label media

# Trigger sketchybar events
yabai -m signal --add event=space_changed    action="sketchybar --trigger space_change"
yabai -m signal --add event=display_changed  action="sketchybar --trigger space_change"
yabai -m signal --add event=window_focused   action="sketchybar --trigger window_focus"
yabai -m signal --add event=application_front_switched action="sketchybar --trigger window_focus"
