# Custom config for my own script
# https://github.com/matejstastny/bin/blob/main/bin/remote

[[hosts]]
name = "rover"
host = "192.168.0.146"
user = "trickfire"
path = "/home/trickfire/urc-2023"
tags = ["trickfire"]
password = "trickfire"
