# --------------------------------------------------------------------------------------------
# starship.toml - clean prompt
# --------------------------------------------------------------------------------------------

format = """\
$directory\
$git_branch\
$git_status\
$character\
"""

add_newline = true

[character]
success_symbol = "[>](bold white)"
error_symbol = "[>](bold red)"

[directory]
format = "[$path]($style) "
truncation_length = 3
style = "bold cyan"
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"
symbol = ""

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold yellow"
disabled = false

[nodejs]
disabled = true

[python]
disabled = true

[java]
disabled = true

[c]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[docker_context]
disabled = true
