# --------------------------------------------------------------------------------------------
# starship.toml
# --------------------------------------------------------------------------------------------
# Author: Matej Stastny
# Date: 2026-02-01 (YYYY-MM-DD)
# License: MIT
# Link: https://github.com/matejstastny/dotfiles
# --------------------------------------------------------------------------------------------

add_newline = true
command_timeout = 2000

format = """$env_var$os$username$hostname$kubernetes$directory$git_branch$git_status$python$nodejs$rust$golang$java$kotlin$lua$ruby$php$swift$zig$dart$elixir$crystal$nim$scala$haskell$julia$ocaml$perl$erlang$c$dotnet$bun$deno$terraform$docker_context$package
$character
"""

[character]
success_symbol = "╰⎯"
error_symbol = "╰⎯"


[env_var]
symbol = "╭╴"
variable = 'SHELL'
format = "$symbol"
disabled = false

# ---

[os]
format = '[$symbol](bold #DCD7BA) '
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'

# ---

# Shows the username
[username]
style_user = 'yellow bold'
style_root = 'black bold'
format = '[//](#727169) [$user](#D73B3E) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[//](#727169) [$hostname](bold #957FB8) '
disabled = false

# Shows current directory
[directory]
truncation_length = 0
truncation_symbol = ''
home_symbol = '~'
read_only = '  '
format = '[//](#727169) [$path]($style)[$read_only]($read_only_style) '
style = '#7FB4CA'


# Shows current git branch
[git_branch]
# symbol = ''
symbol = ''
format = '[//](#727169) [$symbol\[$branch\]]($style) '
style = 'bold #D73B3E'

# Shows current git status
[git_status]
disabled = true
format = '[ $all_status $ahead_behind]($style) '
style = 'bold #98BB6C'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold #957FB8) '
disabled = false

# ---


[python]
symbol = '󰌠'
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
format = '[//](#727169) [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[nodejs]
symbol = '󰎙'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#98BB6C'

[rust]
symbol = '󱘗'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E46876'

[golang]
symbol = '󰟓'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#7FB4CA'

[java]
symbol = '󰬷'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E46876'

[kotlin]
symbol = '󱈙'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#957FB8'

[lua]
symbol = '󰢱'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#7E9CD8'

[ruby]
symbol = '󰴭'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E46876'

[php]
symbol = '󰌟'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#957FB8'

[swift]
symbol = '󰛥'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#FFA066'

[zig]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E6C384'

[dart]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#7FB4CA'

[elixir]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#957FB8'

[crystal]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#DCD7BA'

[nim]
symbol = '󰆥'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E6C384'

[scala]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E46876'

[haskell]
symbol = '󰲒'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#957FB8'

[julia]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#98BB6C'

[ocaml]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E6C384'

[perl]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#7FB4CA'

[erlang]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#E46876'

[c]
symbol = ''
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#7E9CD8'

[dotnet]
symbol = '󰪮'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#957FB8'

[bun]
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#DCD7BA'

[deno]
symbol = '🦕'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#DCD7BA'

[terraform]
symbol = '󱁢'
format = '[//](#727169) [$symbol ($version)]($style) '
style = '#957FB8'

[docker_context]
symbol = '󰡨'
format = '[//](#727169) [$symbol $context]($style) '
style = '#7FB4CA'

[package]
symbol = '󰏗'
format = '[//](#727169) [$symbol $version]($style) '
style = '#FFA066'
