[styles]
theme = "custom"

[styles.cpu]
all_entry_color = "#7E9CD8"
avg_entry_color = "#957FB8"

[styles.memory]
ram_color = "#98BB6C"
cache_color = "#7AA89F"
swap_color = "#FFA066"
arc_color = "#E6C384"
gpu_colors = ["#957FB8", "#D27E99", "#7FB4CA"]

[styles.network]
rx_color = "#98BB6C"
tx_color = "#E46876"
rx_total_color = "#76946A"
tx_total_color = "#C34043"

[styles.battery]
high_battery_color = "#98BB6C"
medium_battery_color = "#E6C384"
low_battery_color = "#C34043"

[styles.tables]
headers = { color = "#DCD7BA", bold = true }

[styles.graphs]
graph_color = "#363646"
border_color = "#363646"
selected_text_color = "#DCD7BA"
text_color = "#C8C093"
widget_title_color = "#7E9CD8"
highlighted_border_color = "#7E9CD8"
disabled_text_color = "#727169"
