ARCH=$(uname -m)
OS_TYPE="$(uname)"

DOTFILES_DIR="$HOME/dotfiles"
ASSETS_DIR="$DOTFILES_DIR/assets"
FONT_DIR="$ASSETS_DIR/fonts"
CONFIGS_DIR="$DOTFILES_DIR/configs"
WALLPAPER_DIR="$ASSETS_DIR/wallpapers"

BREWFILE="$DOTFILES_DIR/Brewfile"
WALLPAPER="$WALLPAPER_DIR/mac-wallpaper.jpg"
