# --------------------------------------------------------------------------------------------
# hyprpaper.conf - my Hyprpaper config (wallpaper daemon)
# --------------------------------------------------------------------------------------------
# Author: Matej Stastny
# License: MIT
# Link: https://github.com/matejstastny/dotfiles
# --------------------------------------------------------------------------------------------

# Change the path below to your preferred wallpaper
preload = ~/dotfiles/assets/wallpapers/mac-wallpaper.jpg

# Set for all monitors (leave monitor field empty)
wallpaper = ,~/dotfiles/assets/wallpapers/mac-wallpaper.jpg

# IPC allows changing wallpaper at runtime via hyprctl
ipc = on
